name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.5

    - uses: Gr1N/setup-poetry@v7
      with:
        poetry-version: 1.1.13

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        poetry export --dev --without-hashes --format requirements.txt --output requirements.txt

    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3

  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.2-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.5

    - uses: Gr1N/setup-poetry@v7
      with:
        poetry-version: 1.1.13

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: |
        poetry export --dev --without-hashes --format requirements.txt --output requirements.txt
        pip install -r requirements.txt

    - name: Copy example.env .env
      run: |
        cp example.env .env

    - name: Collect statics
      run: |
        python manage.py collectstatic

    - name: Run migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests
      run: |
        pytest -x .
